import { AttendanceRecord, AttendanceStats } from "../../types/attendance";
import { LeaveBalance, LeaveRequest, LeaveType } from "../../types/leave";

export const mockLeaveTypes: LeaveType[] = [
  {
    id: "1",
    name: "Annual Leave",
    code: "AL",
    description: "Yearly vacation days",
    maxDays: 25,
    isCarryForward: true,
    requiresApproval: true,
    requiresDocument: false,
    color: "bg-blue-500",
    icon: "Calendar",
  },
  {
    id: "2",
    name: "Sick Leave",
    code: "SL",
    description: "Medical leave",
    maxDays: 12,
    isCarryForward: false,
    requiresApproval: false,
    requiresDocument: true,
    color: "bg-red-500",
    icon: "Heart",
  },
  {
    id: "3",
    name: "Personal Leave",
    code: "PL",
    description: "Personal time off",
    maxDays: 5,
    isCarryForward: false,
    requiresApproval: true,
    requiresDocument: false,
    color: "bg-green-500",
    icon: "User",
  },
  {
    id: "4",
    name: "Maternity Leave",
    code: "ML",
    description: "Maternity leave",
    maxDays: 90,
    isCarryForward: false,
    requiresApproval: true,
    requiresDocument: true,
    color: "bg-pink-500",
    icon: "Heart",
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: "1",
    employeeId: "emp1",
    employeeName: "John Doe",
    date: "2024-01-15",
    clockIn: "09:00:00",
    clockOut: "17:30:00",
    breakStart: "12:00:00",
    breakEnd: "13:00:00",
    totalHours: 8.5,
    workingHours: 7.5,
    breakHours: 1,
    overtimeHours: 0,
    status: "present",
    location: {
      latitude: 40.7128,
      longitude: -74.006,
      address: "123 Office Street, New York, NY",
      accuracy: 10,
    },
    notes: "",
    isRemote: false,
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T17:30:00Z",
  },
  {
    id: "2",
    employeeId: "emp1",
    employeeName: "John Doe",
    date: "2024-01-16",
    clockIn: "09:15:00",
    clockOut: "17:45:00",
    breakStart: "12:30:00",
    breakEnd: "13:15:00",
    totalHours: 8.5,
    workingHours: 7.75,
    breakHours: 0.75,
    overtimeHours: 0.25,
    status: "late",
    location: {
      latitude: 40.7128,
      longitude: -74.006,
      address: "123 Office Street, New York, NY",
      accuracy: 15,
    },
    notes: "Traffic jam",
    isRemote: false,
    createdAt: "2024-01-16T09:15:00Z",
    updatedAt: "2024-01-16T17:45:00Z",
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "emp1",
    employeeName: "John Doe",
    employeeEmail: "john.doe@company.com",
    leaveType: mockLeaveTypes[0],
    startDate: "2024-02-01",
    endDate: "2024-02-05",
    totalDays: 5,
    reason: "Family vacation",
    status: "pending",
    appliedDate: "2024-01-20",
    documents: [],
    isHalfDay: false,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "2",
    employeeId: "emp1",
    employeeName: "John Doe",
    employeeEmail: "john.doe@company.com",
    leaveType: mockLeaveTypes[1],
    startDate: "2024-01-10",
    endDate: "2024-01-12",
    totalDays: 3,
    reason: "Flu symptoms",
    status: "approved",
    appliedDate: "2024-01-09",
    approvedBy: "Manager",
    approvedDate: "2024-01-09",
    documents: [],
    isHalfDay: false,
    createdAt: "2024-01-09T08:00:00Z",
    updatedAt: "2024-01-09T14:00:00Z",
  },
];

export const mockLeaveBalances: LeaveBalance[] = [
  {
    employeeId: "emp1",
    leaveTypeId: "1",
    leaveTypeName: "Annual Leave",
    totalAllowed: 25,
    used: 8,
    remaining: 17,
    pending: 5,
    carriedForward: 3,
    year: 2024,
  },
  {
    employeeId: "emp1",
    leaveTypeId: "2",
    leaveTypeName: "Sick Leave",
    totalAllowed: 12,
    used: 3,
    remaining: 9,
    pending: 0,
    carriedForward: 0,
    year: 2024,
  },
  {
    employeeId: "emp1",
    leaveTypeId: "3",
    leaveTypeName: "Personal Leave",
    totalAllowed: 5,
    used: 1,
    remaining: 4,
    pending: 0,
    carriedForward: 0,
    year: 2024,
  },
];

export const attendanceStats: AttendanceStats = {
  totalDays: 30,
  presentDays: 28,
  absentDays: 1,
  lateDays: 3,
  totalHours: 224,
  averageHours: 8.0,
  overtimeHours: 12,
  attendancePercentage: 93.3,
};
